---
title: "registration"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{registration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Growth Data

```{r growth}
library(tf)

growth_female <- subset(growth, gender == "female", select = height)
growth_female$height_mean <- mean(growth_female$height)
growth_female$growth_mean <- tf_derive(growth_female$height_mean)
growth_female$growth <- tf_derive(growth_female$height)
growth_female$growth_warp <- tf_register(growth_female$growth)
growth_female$growth_reg <- tf_unwarp(
  growth_female$growth,
  growth_female$growth_warp
)

n <- nrow(growth_female)

par(mfrow = c(1, 1))
plot(
  growth_female$growth,
  main = "Female Growth Rate Trajectories",
  xlab = "Age (years)",
  ylab = "Growth Rate (cm/year)",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1
)

plot(
  growth_female$growth_warp,
  xlab = "Clock Year",
  ylab = "Biological Year",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1,
)
abline(0, 1, lty = 2)
grid()

plot(
  growth_female$growth_reg,
  main = "Registered Female Growth Curves",
  xlab = "Age (years)",
  ylab = "Growth Rate (cm/year)",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1
)
grid()

oldpar <- par(mfrow = c(1, 2), pty = "s", ask = FALSE)
on.exit(par(oldpar))
for (i in seq_len(nrow(growth_female))) {
  plot(
    growth_female[i, "growth"],
    xlim = c(0, 18),
    main = paste("Growth Case", i),
    xlab = "Age (years)",
    ylab = "Growth Rate (cm/year)",
    lwd = 1.5,
    col = 4,
    bty = "l",
    las = 1
  )
  lines(growth_female$growth_mean, lty = 2, col = 2)
  lines(growth_female[i, "growth_reg"], col = 3)
  plot(
    growth_female[i, "growth_warp"],
    xlab = "Clock Year",
    ylab = "Biological Year",
    lwd = 1.5,
    bty = "l",
    las = 1,
  )
  abline(0, 1, lty = 2)
}

var_pre <- tf_fvar(growth_female$growth)
var_post <- tf_fvar(growth_female$growth_reg)
var_red <- sum(var_post) / sum(var_pre)
print(sprintf("Variance reduction: %.2f%%", 100 * (1 - var_red)))
```

## Gait Data

```{r gait}
gait$knee_angle_warp <- tf_register(gait$knee_angle)
gait$hip_angle_warp <- tf_register(gait$hip_angle)
gait$knee_angle_reg <- tf_unwarp(gait$knee_angle, gait$knee_angle_warp)
gait$hip_angle_reg <- tf_unwarp(gait$hip_angle, gait$hip_angle_warp)

n <- nrow(gait)

par(mfrow = c(1, 1))
plot(
  gait$hip_angle,
  main = "Hip Angles During Gait Cycle",
  xlab = "Gait Cycle (%)",
  ylab = "Hip Angle (degrees)",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1
)
grid()

plot(
  gait$hip_angle_warp,
  main = "Hip Angle Warping Functions",
  xlab = "Original Gait Cycle (%)",
  ylab = "Registered Gait Cycle (%)",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1,
)
abline(0, 1, lty = 2)
grid()

plot(
  gait$hip_angle_reg,
  main = "Registered Hip Angles",
  xlab = "Gait Cycle (%)",
  ylab = "Hip Angle (degrees)",
  lwd = 1.5,
  col = seq_len(n),
  bty = "l",
  las = 1
)
grid()

oldpar <- par(mfrow = c(1, 2), pty = "s", ask = FALSE)
on.exit(par(oldpar))
for (i in seq_len(n)) {
  plot(
    gait[i, "hip_angle"],
    main = paste("Hip Angle Case", i),
    xlab = "Gait Cycle (%)",
    ylab = "Hip Angle (degrees)",
    lwd = 1.5,
    col = 4,
    bty = "l",
    las = 1
  )
  lines(gait$hip_mean, lty = 2, col = 2)
  lines(gait[i, "hip_angle_reg"], col = 3)

  plot(
    gait[i, "hip_angle_warp"],
    main = paste("Warping Case", i),
    xlab = "Original Gait Cycle (%)",
    ylab = "Registered Gait Cycle (%)",
    lwd = 1.5,
    bty = "l",
    las = 1,
  )
  abline(0, 1, lty = 2)
}

var_pre <- tf_fvar(gait$hip_angle)
var_post <- tf_fvar(gait$hip_angle_reg)
var_red <- sum(var_post) / sum(var_pre)
print(sprintf("Variance reduction hip angle: %.2f%%", 100 * (1 - var_red)))

var_pre <- tf_fvar(gait$knee_angle)
var_post <- tf_fvar(gait$knee_angle_reg)
var_red <- sum(var_post) / sum(var_pre)
print(sprintf("Variance reduction knee angle: %.2f%%", 100 * (1 - var_red)))
```