---
title: "simulation study"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{registration}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r simulation-study, eval = FALSE}
library(checkmate)
library(dplyr)
library(purrr)
library(tf)

#' Integrated Root Mean Squared Error
#'
#' @details
#' The Integrated Root Mean Squared Error is defined as \deqn{
#'   \sqrt{\int\left(\hat{f}_i(t)-f_i(t)\right)^2 d t}
#' }
tf_irmse <- function(truth, response) {
  assert_class(truth, "tfd")
  assert_class(response, "tfd")
  sqrt(tf_integrate((response - truth)^2))
}

tf_rgam <- function(n, arg = 51L, sigma = 0.1) {
  rlang::check_installed("fdasrvf")
  n <- assert_count(n, positive = TRUE, coerce = TRUE)
  arg <- assert_count(arg, positive = TRUE, coerce = TRUE)
  assert_number(sigma)

  x <- fdasrvf::rgam(N = arg, sigma = sigma, num = n)
  tfd(x, arg = seq(0, 1, length.out = arg))
}

# function recovery
# step 1. data generating process (20-50 replications)
# step 2. apply warping to simulated curves
# step 3. apply registration to warped curves
# step 4. compute IRMSE between original and registered curves

# NOTE eigenvalue crit 2 can only work for DGP 1 and DGP 2

#' DGP with only phase variation
dgp_phase_only <- function(n = 20L, arg = 51L, sigma = 0.1) {
  x <- seq(-3, 3, length.out = 51)
  x <- sapply(seq_len(n), function(i) sin(x))
  x <- as.tfd(t(x))

  domain <- tf_domain(x)
  warp <- tf_rgam(n, arg = arg, sigma = sigma)
  warp <- domain[1] + (domain[2] - domain[1]) * warp
  warp <- tfd(tf_evaluations(warp), arg = tf_arg(x))
  unreg <- tf_warp(x, warp)
  list(reg = x, unreg = unreg, warp = warp)
}

#' DPG with rank-1 amplitude and phase variation
dgp_phase_rank1 <- function(n = 20L, arg = 51L, sigma = 0.1) {
  x <- seq(-3, 3, length.out = arg)
  x <- sapply(seq_len(n), function(i) {
    amplitude <- runif(1, 0.8, 1.2)
    amplitude * sin(x)
  })
  x <- as.tfd(t(x))

  domain <- tf_domain(x)
  warp <- tf_rgam(n, arg = arg, sigma = sigma)
  warp <- domain[1] + (domain[2] - domain[1]) * warp
  warp <- tfd(tf_evaluations(warp), arg = tf_arg(x))
  unreg <- tf_warp(x, warp)
  list(reg = x, unreg = unreg, warp = warp)
}

#' DGP with complex phase variation
dgp_complex <- function() {}

run_recovery <- function(data, params) {
  imap(params, function(pv, method) {
    i <- 0L
    res <- pmap(pv, function(...) {
      i <<- i + 1L
      pv <- list(...)
      runtime <- system.time({
        warp_pred <- do.call(
          tf_register,
          c(list(.x = data$unreg, .method = method), pv)
        )
      })
      x_pred <- tf_unwarp(data$unreg, warp_pred)
      tibble(
        param_id = i,
        param_set = list(pv),
        mean = tf_irmse(mean(data$reg), mean(x_pred)),
        fn = mean(tf_irmse(data$reg, x_pred)),
        warp = mean(tf_irmse(data$warp, warp_pred)),
        runtime = unname(runtime["elapsed"])
      )
    })
    res |> list_rbind() |> mutate(method = method, .before = 1L)
  })
}

run_benchmark <- function(data, params, iter = 20L) {
  bmr <- map(seq_len(iter), function(i) {
    run_recovery(data, params) |>
      list_rbind() |>
      mutate(iter = i, .before = 1L)
  })
  list_rbind(bmr)
}

# set experiment design
srvf_params <- expand.grid(
  penalty_method = c("roughness", "geodesic"),
  centroid_type = c("mean", "median"),
  parallel = c(TRUE, FALSE),
  stringsAsFactors = FALSE
)
fda_params <- data.frame(crit = 1:2)
params <- list(srvf = srvf_params, fda = fda_params)

# create DGPs
sim_one <- dgp_phase_only()
sim_two <- dgp_phase_rank1()

# run benchmark
bmr_one <- run_benchmark(sim_one, params, iter = 50L) |>
  mutate(data = "phase_only")
bmr_two <- run_benchmark(sim_two, params, iter = 50L) |>
  mutate(data = "phase_rank1")
bmr <- bind_rows(bmr_one, bmr_two)

cols <- c("fn", "mean", "warp", "runtime")
aggr <- bmr |>
  summarise(
    across(all_of(cols), list(mean = mean, sd = sd, median = median, mad = mad)),
    .by = c(data, method, param_id)
  )
aggr |> select(data, method, starts_with("runtime"))
```

```{r, eval = FALSE}
library(ggplot2)

bmr_one |>
  tidyr::pivot_longer(cols = c(mean, fn, warp, runtime), names_to = "metric") |>
  mutate(param_id = as.factor(param_id)) |>
  filter(method == "srvf", metric == "fn") |>
  ggplot(aes(param_id, value)) +
  geom_boxplot() +
  labs(
    x = "",
    y = "IRMSE",
    title = "Benchmark One: IRMSE by Parameter Set"
  ) +
  theme_classic()

bmr_one |>
  tidyr::pivot_longer(cols = c(mean, fn, warp, runtime), names_to = "metric") |>
  mutate(param_id = as.factor(param_id)) |>
  filter(method == "srvf") |>
  ggplot(aes(metric, value)) +
  geom_boxplot() +
  labs(x = "", y = "", title = "Benchmark One: Metric by Type") +
  theme_classic()
```
