bibentries <- c(
  sun2012exact = bibentry("article",
    title = "Exact fast computation of band depth for large functional datasets: How quickly can one million curves be ranked?",
    author = "Sun, Ying and Genton, Marc G and Nychka, Douglas W",
    journal = "Stat",
    volume = "1",
    number = "1",
    pages = "68--74",
    year = "2012",
    publisher = "Wiley Online Library"
  ),
  lopez2009concept = bibentry("article",
    title = "On the concept of depth for functional data",
    author = "L\u00f3pez-Pintado, Sara and Romo, Juan",
    journal = "Journal of the American statistical Association",
    volume = "104",
    number = "486",
    pages = "718--734",
    year = "2009",
    publisher = "Taylor & Francis"
  ),
  meng2023mogsa = bibentry("manual",
    title = "\\code{mogsa}: Multiple omics data integrative clustering and gene set analysis",
    author = "Chen Meng",
    year = "2023",
    url = "\\url{https://bioconductor.org/packages/mogsa}",
    doi = "10.18129/B9.bioc.mogsa",
  ),
  swihart2010lasagna = bibentry("article",
    title = "Lasagna plots: a saucy alternative to spaghetti plots",
    author = "Swihart, Bruce J and Caffo, Brian and James, Bryan D and Strand, Matthew and Schwartz, Brian S and Punjabi, Naresh M",
    journal = "Epidemiology (Cambridge, Mass.)",
    volume = "21",
    number = "5",
    pages = "621--625",
    year = "2010",
    publisher = "NIH Public Access"
  )
)
